language: python
python:
  - 3.3

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=docs
  - TOXENV=flake

install:
    # Install iverilog package.
  - sudo add-apt-repository -y ppa:mithro/iverilog-backport
  - sudo apt-get update
  - sudo apt-get install iverilog
  - iverilog -v; true
    # Build the vpi module.
  - (cd vpi; make; sudo make install)
    # Install verilator package
  - sudo apt-get install verilator
  - verilator --version; true
  - pip install tox
  - pip install coveralls

script:
  # Run tests
  - tox

after_success:
  - coveralls
