sudo: false
language: python
python:
    - 3.4
env:
    - TOXENV=py34
    - TOXENV=docs
    - TOXENV=flake
addons:
    apt:
        packages:
            - flex
            - libreadline-dev
            - tcl-dev
            - llvm-3.4-dev
            - libedit-dev
            - verilator
before_install:
    - export PATH=$HOME/bin:$PATH
install:
    - pip install -U pip
    - pip install tox
    - pip install coveralls
    - llvm-config --version
    - llvm-config --components
    - wget https://github.com/nickg/nvc/releases/download/r1.1.0/nvc-1.1.0.tar.gz
    - tar -xzvf nvc-1.1.0.tar.gz
    - pushd nvc-1.1
    - ./tools/fetch-ieee.sh && ./configure --prefix=$HOME
    - make && make install
    - mkdir -p $HOME/.nvc/lib
    - ./tools/build-2008-support.rb
    - popd
script:
    - tox
after_success:
    - coveralls
