sudo: false
language: python
python:
    - 3.5
env:
    global:
    - LLVM_VERSION=5.0
    - LLVM_CONFIG="/usr/bin/llvm-config-${LLVM_VERSION}"
    matrix:
    - TOXENV=py35
    - TOXENV=docs
cache:
    - $HOME/.nvc/lib
    - $HOME/opt
addons:
    apt:
        sources:
            - llvm-toolchain-trusty-5.0
        packages:
            - flex
            - libreadline-dev
            - tcl-dev
            - llvm-5.0-dev
            - libedit-dev
            - verilator
before_install:
    - export PATH=$HOME/bin:$PATH
install:
    - pip install -U pip
    - pip install tox
    - pip install setuptools==26.1
    - pip install coveralls
    - llvm-config --version
    - llvm-config --components
    - ./install_nvc.sh
script:
    - tox
after_success:
    - coveralls
