sudo: false
language: python
python:
    - 3.5
env:
    - TOXENV=py35
    - TOXENV=docs
cache:
    - $HOME/.nvc/lib
    - $HOME/opt
addons:
    apt:
        packages:
            - flex
            - libreadline-dev
            - tcl-dev
            - llvm-3.4-dev
            - libedit-dev
            - verilator
before_install:
    - export PATH=$HOME/bin:$PATH
install:
    - pip install -U pip
    - pip install tox
    - pip install setuptools==26.1
    - pip install coveralls
    - llvm-config --version
    - llvm-config --components
    - ./install_nvc.sh
script:
    - tox
after_success:
    - coveralls
