language: python
python:
  - 3.3

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=docs
  - TOXENV=flake

#addons:
#  apt:
#    sources:
#      ppa:team-electronics/ppa
#    packages:
#      - iverilog
#      - verilator
#sudo: false

before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update
install:
  - sudo apt-get install iverilog-daily
  - sudo apt-get install verilator
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls
