language: python
python:
  - 3.4

install:
  # Install iverilog package.
  - sudo add-apt-repository -y ppa:mithro/iverilog-backport
  - sudo apt-get update
  - sudo apt-get install iverilog
  - iverilog -v; true
  # Build the vpi module.
  - (cd vpi; make; sudo make install)
  # Install verilator package
  - sudo apt-get install verilator
  - verilator --version; true
  - pip install -r dev-requirements.txt
  - pip install .

script:
  # Run tests
  - nose2 -v --with-coverage
  # Generate HTML documentation
  - make -C doc html

after_success:
  - coveralls
