package:
  name: migen
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install

requirements:
  build:
    - python 3.5.*
  run:
    - python 3.5.*

test:
  imports:
    - migen

about:
  home: http://m-labs.hk/gateware.html
  license: 3-clause BSD
  summary: 'A Python toolbox for building complex digital hardware'
